chatapp/urls.py
from django.urls import path,include
from . import views



urlpatterns = [
   
    path('',views.index,name='index'),
    path('create-group/',views.create_chatroom,name='create-group'),
    path('register/',views.register , name ='register'),
    path('login/',views.user_login , name ='user_login'),
    path('logout/',views.user_logout , name ='user_logout'),
    path('<slug:slug>/',views.chatroom,name='chatroom'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from chatapp import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path("",views.index , name ="home"),
    path('rooms/',include('chatapp.urls')),
]

chatapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Chatroom(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    created_time = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_time',)




class ChatMessage(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    room = models.ForeignKey(Chatroom , on_delete= models.CASCADE)
    message_content = models.TextField()
    date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('date',)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')
    bio = models.TextField(max_length=500 , blank=True)

    def __str__(self):
        return self.user.username

chatapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Chatroom,UserProfile

class ChatroomForm(forms.ModelForm):
    class Meta:
        model = Chatroom
        fields = ['name', 'slug']

    def clean_slug(self):
        slug = self.cleaned_data['slug']
        if Chatroom.objects.filter(slug=slug).exists():
            raise forms.ValidationError('This slug is already in use.')
        return slug


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('first_name' ,'last_name','username','email','password')


class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfile
        fields = ('avatar','bio')

chatapp/views.py
from django.shortcuts import render,redirect
from .models import Chatroom,ChatMessage
from django.http import HttpResponse,HttpResponseForbidden,HttpResponseRedirect
from .models import Chatroom
from django.db import IntegrityError
from .forms import ChatroomForm,UserForm ,UserProfileForm
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login ,logout


def index(request):
    chatrooms = Chatroom.objects.all()
    
    return render (request ,'chatapp/index.html',{'chatrooms':chatrooms})

@login_required
def chatroom(requset,slug):
    chatroom = Chatroom.objects.get(slug=slug)
    messages = ChatMessage.objects.filter(room = chatroom)[0:10]
    return render (requset , "chatapp/room.html",{'chatroom':chatroom ,'messages':messages})



    

@login_required
def create_chatroom(request):
    if request.method == 'POST':
        form = ChatroomForm(request.POST)
        if form.is_valid():
            form.save()
            #messages.success(request, 'Chatroom created successfully!')
            return redirect('index')  
        else:
            messages.error(request, 'Chatroom creation failed. Nick-Name Alreasy Exist.')
    else:
        form = ChatroomForm()

    return render(request, 'chatapp/create_group.html', {'form': form})

##########################################################################################################################
#############################################################################################
###################################################################
##########################################
####################

def register(request):
    registered = False
    
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            # Create a user object but don't save it yet
            user = user_form.save(commit=False)
            
            # Set the password using set_password() method
            password = user_form.cleaned_data['password']
            user.set_password(password)

            # Save the user object
            user.save()

            # Proceed with saving the profile form and other data
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'avatar' in request.FILES:
                profile.avatar = request.FILES['avatar']

            profile.save()

            registered = True
            return redirect('index')
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered,
    }
    
    return render(request, 'chatapp/register.html', context)




def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username,password)

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('index')  # Replace 'index' with the appropriate URL name or path
        else:
            messages.error(request, 'Invalid username or password.')

    return render(request, 'chatapp/login.html')


def user_logout(request):
    logout(request)
    # Redirect to the desired page after logout
    return redirect('index')

chatapp/templates/chatapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
</head>
<body>

    
<nav class="bg-white border-gray-200 dark:bg-gray-900">
    <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl p-4">
        <a href="" class="flex items-center">
            <img src="https://flowbite.com/docs/images/logo.svg" class="h-8 mr-3" alt="Flowbite Logo" />
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">CloseCircle</span>
        </a>
        <div class="flex items-center">
            
            <a href="tel:5541251234" class="mr-6 text-sm  text-gray-500 dark:text-white hover:underline">(555) 412-1234</a>
        {% if user.is_authenticated %}
            <a href="{% url 'user_logout' %}" class="text-sm text-blue-600 dark:text-blue-500 hover:underline">Logout</a>
        {% else %}
            <a href="{% url 'user_login' %}" class="text-sm text-blue-600 dark:text-blue-500 hover:underline">Login</a>
        {% endif %}
        
        </div>
    </div>
</nav>
<nav class="bg-gray-50 dark:bg-gray-700">
    <div class="max-w-screen-xl px-4 py-3 mx-auto">
        <div class="flex items-center">
            <ul class="flex flex-row font-medium mt-0 mr-6 space-x-8 text-sm">
                <li>
                    <a href="#" class="text-gray-900 dark:text-white hover:underline" aria-current="page">Home</a>
                </li>
                <li>
                    <a href="{% url 'index' %}" class="text-gray-900 dark:text-white hover:underline">List of Topic</a>
                </li>
                <li>
                    <a href="{% url 'create-group' %}" class="text-gray-900 dark:text-white hover:underline">New Topic</a>
                </li>
                <li>
                    <a href="{% url 'register' %}" class="text-gray-900 dark:text-white hover:underline">Register</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

    {% block body %}
    {% endblock %}
</body>
</html>

chatapp/templates/chatapp/create_group.html
{% extends 'chatapp/base.html' %}


{% block body %}


<div class="flex items-center justify-center">
    <h1 class="text-4xl font-bold text-center animate-pulse text-blue-500">Create Your New Room</h1>
  </div>
  
<div class="max-w-md mx-auto">
    <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="POST">
      {% csrf_token %}
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="id_name">
          Name
        </label>
        <input
          class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          id="id_name"
          name="name"
          type="text"
          placeholder="Enter chatroom name"
          required
        />
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="id_slug">
          Short-Name
        </label>
        <input
          class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          id="id_slug"
          name="slug"
          type="text"
          placeholder="Enter chatroom slug"
          required
        />
      </div>
      <div class="flex items-center justify-center">
        <button
          class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
          type="submit"
        >
          Create Chatroom
        </button>
      </div>
    </form>
  </div>
  
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        <div class="flex justify-center   text-red font-bold ">
          {{ message }}
        </div>
      </li>
    {% endfor %}
  </ul>
{% endif %}

{% endblock %}

chatapp/templates/chatapp/index.html
{% extends 'chatapp/base.html' %}

{% block body %}
    <div class="flex justify-center">
        <div class="w-1/2">
            <h1 class="text-3xl font-bold mb-4 text-center">List of Chatrooms</h1>




                    
         
         
            <form method="GET" action="{% url 'index' %}" class="mb-4 flex">
                <div class="flex">
                    <input type="text" name="query" class="w-full px-14 py-2 border border-gray-300 rounded-l-md" placeholder="Search Chatrooms">
                    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-r-md">Search</button>
                </div>
            </form>





            <table class="w-full bg-white border border-gray-200 shadow-md">
                <thead>
                    <tr>
                        <th class="py-2 px-4 bg-gray-200 text-gray-800 font-bold text-center">Chatroom Name</th>
                    </tr>
                </thead>
                <tbody>
                    {% for chatroom in chatrooms %}
                        <tr>
                            <td class="py-2 px-4 border-b border-gray-200 text-center">
                                <a href="{% url 'chatroom' chatroom.slug %}" class="text-blue-500 hover:text-blue-700">
                                    {{ chatroom.name }}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

chatapp/templates/chatapp/login.html
{% extends 'chatapp/base.html' %}



{% block body %}
    <div class="flex justify-center">
        <form action="{% url 'user_login' %}" method="post" class="bg-white p-6 rounded-lg shadow-md">
            {% csrf_token %}
            <label for="username" class="block text-gray-700 text-sm font-bold mb-2">Username</label>
            <input type="text" id="username" name="username" placeholder="Enter Username" class="block w-full p-2 border border-gray-300 rounded mb-4">
            
            <label for="password" class="block text-gray-700 text-sm font-bold mb-2">Password</label>
            <input type="password" id="password" name="password" placeholder="Enter Password" class="block w-full p-2 border border-gray-300 rounded mb-4">
            
            <input type="submit" value="Login" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
        </form>
    </div>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %}class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

chatapp/templates/chatapp/register.html
{% extends 'chatapp/base.html' %}

{% block body %}
    <div class="flex justify-center mt-8">
        <div class="w-1/2">
            <form enctype="multipart/form-data" method="post" class="bg-white p-4 rounded-lg shadow-md shadow-blue">
                {% csrf_token %}
                
                <div class="mb-4">
                    <label for="id_username" class="block text-gray-700 text-sm font-bold mb-2">First Name</label>
                    {{ user_form.first_name }}
                </div>
                <div class="mb-4">
                    <label for="id_username" class="block text-gray-700 text-sm font-bold mb-2">Last Name</label>
                    {{ user_form.last_name }}
                </div>
                
                <div class="mb-4">
                    <label for="id_username" class="block text-gray-700 text-sm font-bold mb-2">Username</label>
                    {{ user_form.username }}
                </div>
                
                <div class="mb-4">
                    <label for="id_email" class="block text-gray-700 text-sm font-bold mb-2">Email</label>
                    {{ user_form.email }}
                </div>
                
                <div class="mb-4 flex">
                    <div class="w-1/2 mr-2">
                        <label for="id_password" class="block text-gray-700 text-sm font-bold mb-2">Password</label>
                        {{ user_form.password }}
                    </div>
                </div>
                
                <div class="w-2/3 ml-2">
                    <label for="id_bio" class="block text-gray-700 text-sm font-bold mb-2">Bio</label>
                    {{ profile_form.bio }}
                </div>
                
                <div class="mb-4">
                    <label for="id_avatar" class="block text-gray-700 text-sm font-bold mb-2">Profile Picture</label>
                    {{ profile_form.avatar }}
                </div>
                
                <div class="flex justify-center">
                    <input type="submit" name="submit" value="Register" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg">
                </div>
            </form>
        </div>
    </div>
    
    <style>
        /* Add blue shadow to form */
        .shadow-blue {
            box-shadow: 0 0 10px blue;
        }
        
        /* Add border and padding to input areas */
        input[type="text"],
        input[type="email"],
        input[type="password"],
        textarea {
            border: 1px solid #ccc;
            padding: 6px;
            width: 100%;
        }
        
        /* Add specific styles to id_bio textarea */
        .id_bio {
            width: 150%;
            border: 1px solid #ccc;
            padding: 6px;
        }
    </style>
{% endblock %}

chatapp/templates/chatapp/room.html
{% extends 'chatapp/base.html' %}
{% block body %}
<div class="flex flex-col justify-center items-center h-screen bg-gray-100">
    <div class="m-10 font-bold text-3xl text-blue-700">
      Chatroom: {{ chatroom.name }}
    </div>
  
    <div class="message-container m-10 overflow-y-auto max-h-[700px] bg-white rounded-lg shadow-lg w-1/2" id="message-container">
      <div id="chat-messages">
        {% for message in messages %}
        <div class="message flex flex-col p-3 m-3 rounded-lg bg-gradient-to-r from-blue-300 to-blue-500">
          <div class="text-sm text-gray-100">
            {{ message.user.username }}
          </div>
          <div class="text-lg text-gray-900">{{ message.message_content }}</div>
          <div class="text-xs text-gray-100">
            {{ message.date }}
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  
    <div class="form-container fixed inset-x-0 bottom-0 bg-green-900 p-2 justify-center items-center ">
      <form method="post" class="flex">
        {% csrf_token %}
        <input class="rounded-md px-4 py-2 mr-2 bg-gray-200 text-gray-900 placeholder-gray-500 focus:outline-none" id="message-input" type="text" name="message" placeholder="Enter message">
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none" id="send-button" type="submit">Send</button>
      </form>
    </div>
  </div>
  
  
{{ chatroom.slug|json_script:"json-chatroomname" }}
{{ request.user.username|json_script:"json-username" }}
<script>
    const chatRoomName = JSON.parse(document.getElementById('json-chatroomname').textContent)
    const username = JSON.parse(document.getElementById('json-username').textContent)
    const chatSocket = new WebSocket(
        'wss://'
        +"close-circle.up.railway.app"
        +'/ws/'
        +chatRoomName
        +'/'
    )
    chatSocket.onmessage= function(e){
        //console.log('This is a message')
        const data = JSON.parse(e.data)
        if(data.message){
            console.log('Recieved message to client is', data.message)
            let html = '<div class="message shadow-lg p-3 m-3 rounded-lg w-1/2 bg-blue-300">' +
                        '<div class="text-sm text-gray-500">' +
                        data.username + ' </div> ' + data.message + '<div class="text-sm text-gray-500">' + 'Now' + '</div>'
            document.getElementById('chat-messages').innerHTML+=html
            scroll()
        }else{
            alert('The message was empty')
        }
    }
    chatSocket.onclose = function(e){
        console.log('Socket closed')
    }

    document.getElementById('send-button').onclick = function(e){
        e.preventDefault()
        const messageInput = document.getElementById('message-input')
        const message = messageInput.value
        console.log(message)
       

        chatSocket.send(JSON.stringify({
            'message':message,
            'username':username,
            'room':chatRoomName

        }))
         messageInput.value= ""
    }

    function scroll(){
        const mcontainer = document.getElementById('message-container')
        mcontainer.scrollTop = mcontainer.scrollHeight

    }
    scroll()

</script>
{% endblock %}